version: 2.1
commands:
  log_into_quay:
    description: Log Docker agent into Quay.io
    steps:
      - run:
          name: Login to Quay
          command: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD quay.io
jobs:
    build-image:        
       executor: docker/docker
       steps: 
        - log_into_quay
workflows:
  commit:
    jobs:
      - build-image
