orbs:
  docker: circleci/docker@1.5.0
version: 2.1
jobs:
  build-and-test:
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Build Docker image
          command: |
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:lastest
            docker images
workflows:
  build-test:
    jobs:
      - build-and-test