version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run:
        name: Login to Quay
        command: docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD quay.io
      - run: Build the image
        command: docker build . -t $CIRCLE_REPO_NAME:1.0
        
#     executor: docker/docker
#     steps: 
#       - setup_remote_docker
#       - checkout
#       - docker/check:
#           registry: "quay.io"
#       - docker/build: 
#           image: my_repo/orb-test
#       - docker/push: 
#           digest-path: /tmp/digest.txt
#           image: my_repo/orb-test
#       - run: 
#           command: "echo \"Digest is: $(</tmp/digest.txt)\"\n"
orbs: 
   docker: circleci/docker@1.5.0
workflows:
  commit:
    jobs:
      - build
