jobs: 
  build-and-push: 
    steps:
      - log_into_quay:
        
#     executor: docker/docker
#     steps: 
#       - setup_remote_docker
#       - checkout
#       - docker/check:
#           registry: "quay.io"
#       - docker/build: 
#           image: my_repo/orb-test
#       - docker/push: 
#           digest-path: /tmp/digest.txt
#           image: my_repo/orb-test
#       - run: 
#           command: "echo \"Digest is: $(</tmp/digest.txt)\"\n"
orbs: 
#   docker: circleci/docker@1.5.0
  base: pjci/base@1.6.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
