orbs:
  docker: circleci/docker@1.5.0
version: 2.1
jobs:
        steps:
            - checkout
            - run:
                  name: Compute version number
                  command: configure-docker-credentials-store
workflows:
  build-and-publish-docker-image:
    jobs:
         - docker/check:
         - docker/publish:
           image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
           registry: quay.io
