jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  test-env-vars:
    jobs:
      - build
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          dockerfile: Dockerfile
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: https://quay.io/gautampachnandahmo
          tag: $CIRCLE_SHA1