version: 2.1
#orbs:
#  docker: circleci/docker@1.5.0
commands:
  log_into_quay:
    description: Log Docker agent into Quay.io
    steps:
      - setup_remote_docker
      - run: 
          name: Check login
          command: if [[ ! -z "$DOCKER_LOGIN" ]]; then  echo "Login Not empty"; else echo "Login Empty" fi
      - run:
          name: Login to Quay
          command: docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD" quay.io
      - run:
          name: Build Image
          command: docker build . -t $CIRCLE_REPO_NAME/$TAG_TO_BUILD
      - run:
          name: Push to remote
          command: docker push $CIRCLE_REPO_NAME/$TAG_TO_BUILD
      - run:
          name: Create manifest
          command: echo $CIRCLE_REPO_NAME/$TAG_TO_BUILD > manifest.txt
jobs:
    build-image:
       docker:
         - image: docker:17.05.0-ce-git
       steps: 
        - log_into_quay
workflows:
  commit:
    jobs:
      - build-image
