orbs:
  docker: circleci/docker@1.5.0
version: 2.1
jobs:
  docker-login:
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Build Docker image
          command: |
            docker login -u="gautampachnandahmo" -p="fZUqYjHNqClQ+AsuCz5hspwzm4xnLw6NSrwrAMAYKC8xW8Xzc3q4x8iH0ySINyQJ" quay.io
workflows:
  build-test:
    jobs:
      - docker-login