orbs:
  docker: circleci/docker@x.y.z
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
     steps:
      - prepare:
        commands:
          run: echo 1
      - docker/publish:
        image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
        update-description: true
