jobs: 
  build-and-push: 
    executor: docker/docker
    steps: 
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          registry: DOCKER_REGISTRY
      - docker/build: 
          image: my_repo/orb-test
      - docker/push: 
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
      - run: 
          command: "echo \"Digest is: $(</tmp/digest.txt)\"\n"
orbs: 
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
