orbs:
  docker: circleci/docker@1.5.0
version: 2.1

jobs:
    prepare-environment:
        steps:
            - checkout
            - run:
                  name: Compute version number
                  command: configure-docker-credentials-store
    build-and-push: 
         - docker/check:
         - docker/publish:
           image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
           registry: quay.io     
workflows:
  version: 2
  build-and-publish-docker-image:
    jobs:
      - prepare-environment
      - build-and-push

