version: 2.1
#orbs:
#  docker: circleci/docker@1.5.0
commands:
  log_into_quay:
    description: Log Docker agent into Quay.io
    steps:
      - setup_remote_docker
      - run: 
          name: Check login
          command: if [[ ! -z "$QUAY_USER" ]]; then  echo "Login Not empty $QUAY_USER"; else echo "Login Empty"; exit 1; fi
      - run:
          name: Check credentials
          command: if [[ ! -z "$QUAY_PASSWORD" ]]; then  echo "Credentials Not empty $QUAY_PASSWORD"; else echo "Credentials Empty"; exit 1; fi
      - run:
          name: test pull
          command: docker pull quay.io/eris/data
      - run:
          name: Login to Quay
          command: docker login quay.io -u="$QUAY_USER" -p="$QUAY_PASSWORD"
      - run:
          name: Build Image
          command: docker build . -t $CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1
      - run:
          name: Push to remote
          command: docker push $CIRCLE_PROJECT_REPONAME/$CIRCLE_SHA1
      - run:
          name: Create manifest
          command: echo $CIRCLE_REPO_NAME/$CIRCLE_SHA1 > manifest.txt
jobs:
    build-image:
       docker:
         - image: docker:17.05.0-ce-git
       steps: 
        - log_into_quay
workflows:
  commit:
    jobs:
      - build-image
