name: Sync Fork

on:
  schedule:
    - cron: '*/2 * * * *' # every 2 min
  workflow_dispatch: # on button click

jobs:
  sync:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: llvm
          base: master
          head: master
